sonar.projectKey=travel-planner-itinerary-service
sonar.projectName=Travel Planner - Itinerary Service
sonar.projectVersion=1.0.0
sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
